name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.3.0
      - name: Download Experience Builder
        run: npx arcgis-lib-downloader -p arcgis-experience-builder -v 1.10
        env:
          ARCGIS_LIB_DOWNLOADER_USERNAME: ${{ secrets.ARCGIS_LIB_DOWNLOADER_USERNAME }}
          ARCGIS_LIB_DOWNLOADER_PASSWORD: ${{ secrets.ARCGIS_LIB_DOWNLOADER_PASSWORD }}
      - name: Unzip Experience Builder
        run: unzip -q arcgis-experience-builder-1.10.zip -d arcgis-experience-builder-1.10
      - name: Copy Custom Widgets
        run: cp -r widgets/* arcgis-experience-builder-1.10/ArcGISExperienceBuilder/client/your-extensions/widgets
      - name: Create App directory
        run: mkdir public && cd public && mkdir apps && cd apps
        working-directory: arcgis-experience-builder-1.10/ArcGISExperienceBuilder/server
      - name: Copy apps
        run: cp -r apps/* arcgis-experience-builder-1.10/ArcGISExperienceBuilder/server/public/apps
      - name: NPM install client folder
        run: npm ci
        working-directory: arcgis-experience-builder-1.10/ArcGISExperienceBuilder/client
      - name: NPM install in server folder
        run: npm ci
        working-directory: arcgis-experience-builder-1.10/ArcGISExperienceBuilder/server
      - name: install any widget dependencies
        run: |
          for d in `find . -mindepth 1 -maxdepth 1 -type d`; do
          echo $d
          cd $d
          if test -f package.json; then
          echo "installing dependencies for `pwd`..."
          npm i
          fi
          cd ..
          done
        working-directory: arcgis-experience-builder-1.10/ArcGISExperienceBuilder/client/your-extensions/widgets
      - name: Build widgets
        run: npm run build:dev
        working-directory: arcgis-experience-builder-1.10/ArcGISExperienceBuilder/client
      - name: Run download script
        run: node -e "require('./server/src/middlewares/dev/apps/app-download.js').zipApp('0', 'app.zip')"
        working-directory: arcgis-experience-builder-1.10/ArcGISExperienceBuilder
      - name: Unzip app zip
        # ExB has non-standard file permissions so use chmod after unzip
        run: |
          unzip -q app.zip -d app
          chmod -R 777 app
        working-directory: arcgis-experience-builder-1.10/ArcGISExperienceBuilder
      - name: Generate screeenshot (optional)
        working-directory: arcgis-experience-builder-1.10/ArcGISExperienceBuilder/app
        continue-on-error: true
        run: |
          npm install --global pageres-cli
          npm install --global serve
          echo "{\"trailingSlash\":true}" > serve.json
          serve . -p 5000 &
          pageres http://localhost:5000/index.html 1024x768 --filename=screenshot --delay=10
      - name: Deploy app zip to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: arcgis-experience-builder-1.10/ArcGISExperienceBuilder/app

